### ISSUE TITLE
MSBuild v4.0 Not supported and possibly why all these other MSBuild issues are happening.

### ISSUE THREAD

**Issue by DennisSmolek** [apache/cordova-windows#274]
Hello, looking through the open issues I think we're all facing somewhat similar versions of the same problem with MSBuildTool. #266, #267, #272, #273 are all versions of problems finding the correct MSBuild path.

I'm running `Ionic 3.20.0` `Cordova 8.0.0` and `Cordova-Windows 6.0.0` as well as a fresh install of Windows 10 pro and Visual Studio Community 2017

When I run `cordova windows build` or `cordova windows run` I get essentially the same issue:

```
C:\Users\dennis\Source\Repos\showman-ionic>cordova build windows
Skip!
MSBuild v4.0 is not supported, aborting.
(node:2108) UnhandledPromiseRejectionWarning: CordovaError: No valid MSBuild was detected for the selected target: Package with specified parameters not found in AppPackages folder
    at C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\lib\build.js:83:29
    at _rejected (C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\node_modules\q\q.js:864:24)
    at C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\node_modules\q\q.js:808:41)
    at C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:2108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I read through everyones issues (even some in german) and #267 is correct that any failure will throw the error either in the CLI or using visual studio, BUT when run inside Visual Studio it doesn't have the errors related to missing or unsupported MSBuild.

When I run `cordova build windows --verbose`

```
C:\Users\dennis\Source\Repos\showman-ionic>cordova build windows --verbose
No scripts found for hook "before_build".
No scripts found for hook "before_prepare".
Checking config.xml and package.json for saved platforms that haven't been added to the project
Config.xml and package.json platforms are the same. No pkg.json modification.
Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
PlatformApi successfully found for platform windows
Checking config.xml for saved plugins that haven't been added to the project
Checking for any plugins added to the project that have not been installed in windows platform
No differences found between plugins added to project and installed in windows platform. Continuing...
Generating platform-specific config.xml from defaults for windows at C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\config.xml
Merging project's config.xml into platform-specific windows config.xml
Merging and updating files from [www, platforms\windows\platform_www] to platforms\windows\www
  copy  www\assets\base\base.css platforms\windows\www\assets\base\base.css (updated file)
//
// *** Copying truncated for clarity ***///
//
  copy  www\service-worker.js platforms\windows\www\service-worker.js (updated file)
Updating icons and splash screens at platforms\windows\images
Prepared windows project successfully
No scripts found for hook "pre_package".
Executing script found in plugin com-intel-security-cordova-plugin for hook "after_prepare": plugins\com-intel-security-cordova-plugin\src\windows\ChooseArch_Windows.js
No scripts found for hook "before_compile".
Reading build config file: C:\Users\dennis\Source\Repos\showman-ionic\build.json
getLatestMatchingMSBuild
getLatestMSBuild
Searching for available MSBuild versions...
Running command: C:\WINDOWS\system32\reg.exe query HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\15.5 /v MSBuildToolsPath
Running command: C:\WINDOWS\system32\reg.exe query HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\15.0 /v MSBuildToolsPath
Running command: C:\WINDOWS\system32\reg.exe query HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0 /v MSBuildToolsPath
Running command: C:\WINDOWS\system32\reg.exe query HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\12.0 /v MSBuildToolsPath
Running command: C:\WINDOWS\system32\reg.exe query HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0 /v MSBuildToolsPath
Skip!
Command finished with error code 1: C:\WINDOWS\system32\reg.exe query,HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\15.0,/v,MSBuildToolsPath
Command finished with error code 1: C:\WINDOWS\system32\reg.exe query,HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\15.5,/v,MSBuildToolsPath
Command finished with error code 1: C:\WINDOWS\system32\reg.exe query,HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0,/v,MSBuildToolsPath
Command finished with error code 1: C:\WINDOWS\system32\reg.exe query,HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\12.0,/v,MSBuildToolsPath
Command finished with error code 0: C:\WINDOWS\system32\reg.exe query,HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0,/v,MSBuildToolsPath
Found MSBuild v4.0 at C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
Using MSBuild v4.0 from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
MSBuild v4.0 is not supported, aborting.
(node:9592) UnhandledPromiseRejectionWarning: CordovaError: No valid MSBuild was detected for the selected target: Package with specified parameters not found in AppPackages folder
    at C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\lib\build.js:83:29
    at _rejected (C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\node_modules\q\q.js:864:24)
    at C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\node_modules\q\q.js:808:41)
    at C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\dennis\Source\Repos\showman-ionic\platforms\windows\cordova\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:9592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

So it seems it can't find my MSBuild info at all. That got me looking around and I found:
[VS 2017 Does not put items into the registry](https://github.com/Microsoft/msbuild/issues/2427)
which is the method `cordova-windows` uses to look for the path. (at least on my machine)

So it goes down the registry list and then finds the MSBuild for .NET which is way old I guess and it bails.

When run inside VS, VS I guess handles this or I'm not exactly sure what's happening. I'm 3 days into Windows Build Voodoo.

Other folks are on fresh machines too, and only install 2017, which NEVER places any info in the registry so it'll likely show as failed... 

I have one thing left to try solution wise but I'm at my limit skillset wise on going much deeper on my own. Let me know what you need / suggest I try and I'll for sure do it.. 

Probably unrelated but I also saw my `CordovaApp.Windows10.jsproj` is still targeting v14:
`<Project DefaultTargets="Build" ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`

Which Seems it [could be bumped to 15](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-toolset-toolsversion) if [2017 is the new Req](https://cordova.apache.org/announcements/2018/02/27/cordova-windows-6.0.0.html)

**Comment by janpio** [comment]
`cordova-windows` uses multiple methods to try to figure out a matching MSBuild version - it's quite a mess and very brittle code, so I am not too surprised it is not working all the time. (But with a default 2017 install - an probably without .NET MSBuild installed - it should definitely work)

 If it can only find the 4.0, your best and easiest best is probably to use the `MSBUILDDIR` or `VSINSTALLDIR` environment variables mentioned in the blog post here: https://cordova.apache.org/announcements/2018/02/27/cordova-windows-6.0.0.html

**Comment by shazron** [comment]
See http://www.visualstudioextensibility.com/2016/11/23/some-implications-of-the-new-modular-setup-of-visual-studio-2017-for-vsx-developers/ :

```
The location of MSBuild for VS 2017 has changed, and can be several of them.
In the past (until Visual Studio 2015), the path of MSBuild was “C:\Program Files (x86)\MSBuild\<version>”, where <version> was “4.0”, “12.0” (VS 2013), “14.0” (VS 2015). 

There is no “15.0” folder there for VS 2017. Instead, MSBuild for VS 2017 is installed in the folder “C:\Program Files (x86)\Microsoft Visual Studio\2017\<edition>\MSBuild\15.0”, where edition can be “Community”, “Professional” or “Enterprise”. 

Again, for your own use on your own build script you can hardcode the path, but if you want to use a more proper way, you need to get the VS 2017 installation folder as explained above and concatenate “MSBuild\15.0”. 

Or you can wait until Microsoft releases a document about how to resolve MSBuild location (they are working on it and now that MSBuild is open source you can follow the progress on GitHub). BTW, you can download the MSBuild Tools for Visual Studio 2017 RC here.
```

So, to have auto-detect working properly we need to add more locations to check as per the article, and only rely on the registry as a fallback. I had VS 2017 Community installed, and it only detected MSBuild v4 from the .NET Framework so I had to use the MSBUILDDIR env var.

**Comment by janpio** [comment]
@edenprojectde No.
@samuelchen Open a new issue and include all available environment information of your system.

**Comment by samuelchen** [comment]
@janpio thanks. I solved it by using environment variable MSBUILDDIR

**Comment by janpio** [comment]
`MSBUILDDIR` and `VSINSTALLDIR` are indeed the solution here if VS17 can not detect MSBuild for any reason. https://github.com/apache/cordova-docs/pull/976 will add this to the documentation.
