### ISSUE TITLE
No valid MSBuild was detected for the selected target

### ISSUE THREAD

**Issue by robertnicjoo** [apache/cordova-windows#339]
Hi,

I was suggested to open issue here [[source](https://github.com/apache/cordova-docs/issues/1001)] the issue i'm facing is that I can't make windows app and i get this error

```
ENV var MSBUILDDIR is set C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
Building project: C:\laragon\www\ionic\WinApp\platforms\windows\CordovaApp.Windows10.jsproj
        Configuration : debug
        Platform      : anycpu
        Buildflags    : /p:AppxBundle=Never
        MSBuildTools  : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
buildProject spawn: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild [ 'C:\\laragon\\www\\ionic\\WinApp\\platforms\\windows\\CordovaApp.Windows10.jsproj',
  '/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal',
  '/nologo',
  '/p:Configuration=debug',
  '/p:Platform=anycpu',
  '/p:AppxBundle=Never' ] { stdio: 'inherit' }
C:\laragon\www\ionic\WinApp\platforms\windows\CordovaApp.Windows10.jsproj(61,13): error MSB4226: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\JavaScript\Microsoft.VisualStudio.WJProject.Default.props" was not found. Also, tried to find "Microsoft\VisualStudio\v15.0\JavaScript\Microsoft.VisualStudio.WJProject.Default.props" in the fallback search path(s) for $(MSBuildExtensionsPath32) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.
No valid MSBuild was detected for the selected target: Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild: Command failed with exit code 1
```

### What I'm using
```
IDE: Visual studio 2017
Cordova 9
cordova-windows 7.0.0
BuildTools 15
OS: Windows 10
Ionic 5
```

### What I did so far

Added MSBUILDDIR in system environments
Added VSINSTALLDIR in system environments
Added path of MSBuild in system environments

Yet I'm getting error above.

**Any idea what might be wrong?**

**Comment by janpio** [comment]
What version of Visual Studio 2017 are you using?
What values did you set the env vars to?

**Comment by robertnicjoo** [comment]
@janpio i downloaded from official website i guess must be latest version.

- i didn't set any values in env i just installed this plugin to my ionic app so it must be set the default values of latest version.

**Comment by robertnicjoo** [comment]
@janpio 


![01](https://user-images.githubusercontent.com/8672823/59323055-3bd8e800-8d03-11e9-8e89-22c9be06a379.png)


**system info**

```
Ionic:

   Ionic CLI                     : 5.0.1 (C:\laragon\bin\nodejs\node-v11\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : windows 7.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 4 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.2

System:

   Android SDK Tools : 26.1.1 (C:\Users\Theo\AppData\Local\Android\sdk)
   NodeJS            : v11.10.0 (C:\laragon\bin\nodejs\node-v11\node.exe)
   npm               : 6.7.0
   OS                : Windows 10
```

**Project package.json**

```
"dependencies": {
   //....
    "cordova-windows": "7.0.0",
    //....
  },
"cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {}
    },
    "platforms": [
      "windows"
    ]
  }
```

**Environment**

![02](https://user-images.githubusercontent.com/8672823/59323251-20221180-8d04-11e9-88f1-afc64ccc2fae.png)
![03](https://user-images.githubusercontent.com/8672823/59323252-20baa800-8d04-11e9-8911-957f1fa3dafe.png)


Hope it helps

**Comment by janpio** [comment]
Please make sure you have the necessary workloads and products installed: https://cordova.apache.org/docs/en/dev/guide/platforms/windows/index.html#visual-studio-2017

**Comment by robertnicjoo** [comment]
@janpio i just installed the sdk

![vc](https://user-images.githubusercontent.com/8672823/59332492-946aae00-8d20-11e9-85d4-bec2a172e72c.png)

here is the result:

```
ENV var VSINSTALLDIR is set C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
Building project: C:\laragon\www\ionic\WinApp\platforms\windows\CordovaApp.Windows10.jsproj
        Configuration : debug
        Platform      : anycpu
        Buildflags    : /p:AppxBundle=Never
        MSBuildTools  : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
buildProject spawn: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild [ 'C:\\laragon\\www\\ionic\\WinApp\\platforms\\windows\\CordovaApp.Windows10.jsproj',
  '/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal',
  '/nologo',
  '/p:Configuration=debug',
  '/p:Platform=anycpu',
  '/p:AppxBundle=Never' ] { stdio: 'inherit' }
  prebuild.js: Patching platform `10`
  - Injected `base.js` reference to `/www/index.html`
  - Removing /( *)(<script\s+(?:type="text\/javascript"\s+)?src="\/\/Microsoft.WinJS.2.0\/js\/base.js">\s*<\/script>)(\s*)/ from /www/index.html
  - Removing /( *)(<script\s+(?:type="text\/javascript"\s+)?src="\/\/Microsoft.Phone.WinJS.2.1\/js\/base.js">\s*<\/script>)(\s*)/ from /www/index.html
No valid MSBuild was detected for the selected target: AppPackages folder doesn't exist
```

**Comment by janpio** [comment]
That's better. 

"Universal Windows Platform development" Workload also selected?

If so try `cordova run windows --archs=x86`.

**Comment by robertnicjoo** [comment]
@janpio 

> "Universal Windows Platform development" Workload also selected?

Where should i select that?

**Comment by janpio** [comment]
On the "Workloads" tab, see the screenshot on https://cordova.apache.org/docs/en/dev/guide/platforms/windows/index.html#visual-studio-2017

**Comment by robertnicjoo** [comment]
@janpio  yes i start to download it sorry for that anyway here is the result of `--verbose`

```
Prepared windows project successfully
No scripts found for hook "after_prepare".
No scripts found for hook "before_compile".
getLatestMatchingMSBuild
getLatestMSBuild
ENV var MSBUILDDIR is set C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
Running command: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild -version -nologo
Command finished with error code 0: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild -version,-nologo
Using MSBuild v15.9 from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
Building project: C:\laragon\www\ionic\WinApp\platforms\windows\CordovaApp.Windows10.jsproj
        Configuration : debug
        Platform      : anycpu
        Buildflags    : /p:AppxBundle=Never
        MSBuildTools  : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
Running command: reg query HKLM\SOFTWARE\Microsoft\Microsoft SDKs\Windows /s /v InstallationFolder /reg:32
Command finished with error code 0: reg query,HKLM\SOFTWARE\Microsoft\Microsoft SDKs\Windows,/s,/v,InstallationFolder,/reg:32
buildProject spawn: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild [ 'C:\\laragon\\www\\ionic\\WinApp\\platforms\\windows\\CordovaApp.Windows10.jsproj',
  '/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal',
  '/nologo',
  '/p:Configuration=debug',
  '/p:Platform=anycpu',
  '/p:AppxBundle=Never' ] { stdio: 'inherit' }
Running command: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild C:\laragon\www\ionic\WinApp\platforms\windows\CordovaApp.Windows10.jsproj /clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal /nologo /p:Configuration=debug /p:Platform=anycpu /p:AppxBundle=Never
  prebuild.js: Patching platform `10`
  - Injected `base.js` reference to `/www/index.html`
  - Removing /( *)(<script\s+(?:type="text\/javascript"\s+)?src="\/\/Microsoft.WinJS.2.0\/js\/base.js">\s*<\/script>)(\s*)/ from /www/index.html
  - Removing /( *)(<script\s+(?:type="text\/javascript"\s+)?src="\/\/Microsoft.Phone.WinJS.2.1\/js\/base.js">\s*<\/script>)(\s*)/ from /www/index.html
Command finished with error code 0: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild C:\laragon\www\ionic\WinApp\platforms\windows\CordovaApp.Windows10.jsproj,/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal,/nologo,/p:Configuration=debug,/p:Platform=anycpu,/p:AppxBundle=Never
No valid MSBuild was detected for the selected target: AppPackages folder doesn't exist
CordovaError: No valid MSBuild was detected for the selected target: AppPackages folder doesn't exist
    at C:\laragon\www\ionic\WinApp\platforms\windows\cordova\lib\build.js:83:29
    at _rejected (C:\laragon\www\ionic\WinApp\node_modules\q\q.js:844:24)
    at C:\laragon\www\ionic\WinApp\node_modules\q\q.js:870:30
    at Promise.when (C:\laragon\www\ionic\WinApp\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\laragon\www\ionic\WinApp\node_modules\q\q.js:788:41)
    at C:\laragon\www\ionic\WinApp\node_modules\q\q.js:604:44
    at runSingle (C:\laragon\www\ionic\WinApp\node_modules\q\q.js:137:13)
    at flush (C:\laragon\www\ionic\WinApp\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
```

**Comment by robertnicjoo** [comment]
@janpio 

Thanks for the helps man it's working now after installing "Universal Windows Platform development"

Here I'd like to share process step by step for others in future.

1. Install `VS17` (vs19 won't work)
2. Install `MSBuild` from VS17 Installation
3. Install `SDK 10` from VS17 Installation
4. Install `Universal Windows Platform development` from VS17 Installation
5. Install `cordova` **globally**
6. Install `cordova-windows` platform
7. Last but not least **restart your system** otherwise you still get the errors

Hope it helps to ease the process for others with the same issue.

**Comment by janpio** [comment]
You can probably skip step 2 - the general `MSBuild` should not be required and probably do more harm than good.

But great it now works for you ❤️
