### ISSUE TITLE
Build command does not report correct status code

### ISSUE THREAD

**Issue by janpio** [apache/cordova-windows#353]
`cordova build windows` and `cordova run windows` do not report an error even when the build clearly failed:

https://travis-ci.org/janpio/cordova-windows-ci/builds/555130991

```
...
Running command: reg query HKLM\SOFTWARE\Microsoft\Microsoft SDKs\Windows /s /v InstallationFolder /reg:32
Command finished with error code 0: reg query,HKLM\SOFTWARE\Microsoft\Microsoft SDKs\Windows,/s,/v,InstallationFolder,/reg:32
buildProject spawn: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild [ 'C:\\Users\\travis\\build\\janpio\\cordova-windows-ci\\platforms\\windows\\CordovaApp.Windows10.jsproj',
  '/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal',
  '/nologo',
  '/p:Configuration=debug',
  '/p:Platform=anycpu',
  '/p:AppxBundle=Never' ] { stdio: 'inherit' }
Running command: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild C:\Users\travis\build\janpio\cordova-windows-ci\platforms\windows\CordovaApp.Windows10.jsproj /clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal /nologo /p:Configuration=debug /p:Platform=anycpu /p:AppxBundle=Never
Command finished with error code 1: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild C:\Users\travis\build\janpio\cordova-windows-ci\platforms\windows\CordovaApp.Windows10.jsproj,/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal,/nologo,/p:Configuration=debug,/p:Platform=anycpu,/p:AppxBundle=Never
CordovaError: No valid MSBuild was detected for the selected target: Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild: Command failed with exit code 1
    at C:\Users\travis\build\janpio\cordova-windows-ci\platforms\windows\cordova\lib\build.js:83:29
    at _rejected (C:\Users\travis\build\janpio\cordova-windows-ci\node_modules\q\q.js:864:24)
    at C:\Users\travis\build\janpio\cordova-windows-ci\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\travis\build\janpio\cordova-windows-ci\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\travis\build\janpio\cordova-windows-ci\node_modules\q\q.js:808:41)
    at C:\Users\travis\build\janpio\cordova-windows-ci\node_modules\q\q.js:624:44
    at runSingle (C:\Users\travis\build\janpio\cordova-windows-ci\node_modules\q\q.js:137:13)
    at flush (C:\Users\travis\build\janpio\cordova-windows-ci\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
The command "cordova build windows --verbose" exited with 0.
```

```
...
Running command: reg query HKLM\SOFTWARE\Microsoft\Microsoft SDKs\Windows /s /v InstallationFolder /reg:32
Command finished with error code 0: reg query,HKLM\SOFTWARE\Microsoft\Microsoft SDKs\Windows,/s,/v,InstallationFolder,/reg:32
buildProject spawn: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild [ 'C:\\Users\\travis\\build\\janpio\\cordova-windows-ci\\platforms\\windows\\CordovaApp.Windows10.jsproj',
  '/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal',
  '/nologo',
  '/p:Configuration=debug',
  '/p:Platform=anycpu',
  '/p:AppxBundle=Never' ] { stdio: 'inherit' }
Running command: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild C:\Users\travis\build\janpio\cordova-windows-ci\platforms\windows\CordovaApp.Windows10.jsproj /clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal /nologo /p:Configuration=debug /p:Platform=anycpu /p:AppxBundle=Never
  prebuild.js: Patching platform `10`
  - Injected `base.js` reference to `/www/index.html`
  - Removing /( *)(<script\s+(?:type="text\/javascript"\s+)?src="\/\/Microsoft.WinJS.2.0\/js\/base.js">\s*<\/script>)(\s*)/ from /www/index.html
  - Removing /( *)(<script\s+(?:type="text\/javascript"\s+)?src="\/\/Microsoft.Phone.WinJS.2.1\/js\/base.js">\s*<\/script>)(\s*)/ from /www/index.html
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(2519,5): warning APPX0105: Cannot import the key file 'CordovaApp_TemporaryKey.pfx'. The key file may be password protected. To correct this, try to import the certificate manually into the current user’s personal certificate store. [C:\Users\travis\build\janpio\cordova-windows-ci\platforms\windows\CordovaApp.Windows10.jsproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(2519,5): warning APPX0107: The certificate specified is not valid for signing. For more information about valid certificates, see http://go.microsoft.com/fwlink/?LinkID=241478. [C:\Users\travis\build\janpio\cordova-windows-ci\platforms\windows\CordovaApp.Windows10.jsproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(2638,5): error APPX0002: Task 'ValidateAppxManifest' failed. Retrieving the COM class factory for component with CLSID {5842A140-FF9F-4166-8F5C-62F5B7B0C781} failed due to the following error: 8007045a A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A). [C:\Users\travis\build\janpio\cordova-windows-ci\platforms\windows\CordovaApp.Windows10.jsproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(2638,5): error APPX0002:  [C:\Users\travis\build\janpio\cordova-windows-ci\platforms\windows\CordovaApp.Windows10.jsproj]
Command finished with error code 1: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild C:\Users\travis\build\janpio\cordova-windows-ci\platforms\windows\CordovaApp.Windows10.jsproj,/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal,/nologo,/p:Configuration=debug,/p:Platform=anycpu,/p:AppxBundle=Never
CordovaError: No valid MSBuild was detected for the selected target: Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild: Command failed with exit code 1
    at C:\Users\travis\build\janpio\cordova-windows-ci\platforms\windows\cordova\lib\build.js:83:29
    at _rejected (C:\Users\travis\build\janpio\cordova-windows-ci\node_modules\q\q.js:864:24)
    at C:\Users\travis\build\janpio\cordova-windows-ci\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\travis\build\janpio\cordova-windows-ci\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\travis\build\janpio\cordova-windows-ci\node_modules\q\q.js:808:41)
    at C:\Users\travis\build\janpio\cordova-windows-ci\node_modules\q\q.js:624:44
    at runSingle (C:\Users\travis\build\janpio\cordova-windows-ci\node_modules\q\q.js:137:13)
    at flush (C:\Users\travis\build\janpio\cordova-windows-ci\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
The command "cordova run windows --verbose" exited with 0.
```

**Comment by tdulcet** [comment]
I have the same issue trying to build an Ionic app with Cordova in Travis CI: https://travis-ci.org/tdulcet/clicker/jobs/481711212. This is related to #354. I have been unable to find a workaround.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
