### ISSUE TITLE
Cordova installation problem

### ISSUE THREAD

**Issue by mysorian** [apache/cordova-windows#399]
# Bug Report

## Problem
Using npm Cordova did not install.
### What is expected to happen?
I must be able to run cardova from command line

### What does actually happen?
An error was thrown and executing c:\cardova -v

## Information

This is the error:
C:\WINDOWS\system32>cordova -v
c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:77
                                throw err;
                                ^

RangeError: Maximum call stack size exceeded
    at Object.mkdirSync (node:fs:1316:19)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:61:12)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:68:5)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:69:12)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:69:12)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:69:12)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:69:12)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:69:12)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:69:12)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:69:12)
---------------------
 Windows registry has reference to some Cardova image files. A few other Cardova related files in the npm folder.

### Command or Code

C:\cardova -v

### Environment, Platform, Device

Windows 10 (x64). npm is installed. Intel Core i7 on a Dell laptop.

### Version information

Visual studio Community2017 and Android Studio Snow cat are installed and working

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by mysorian** [comment]
Finally got the install to work.
The problem was solved by clearing the npm cache using **npm cache clean -f**
Why do I get the Cordova folder created in this folder (C:\Users\TestUser\AppData\Roaming\npm\node_modules\**cordova**)
![Cordova_Folder](https://user-images.githubusercontent.com/5265734/139776735-7670055d-5f26-4e90-b81f-af20f93608c2.jpg)
?
Does the folder look complete?
I suppose it is globally accessible. should I move it to a simpler location (like Program Files)?

**Comment by breautek** [comment]
That's the default path for globally installed packages on windows. I would advise against manually manipulating files, especially if you don't know what you're doing. [Configure NPM](https://docs.npmjs.com/cli/v7/using-npm/config) instead if you prefer the global packages to be installed in a different location.

Closing this issue because it was found that it wasn't a cordova-windows issue.
